id: A11533E3E
title: 'The Pure Three Kāyas Ablaze in Perfect Splendour: A Prayer Based on the Meaning
  of the Great Perfection'
type: translation
pechas:
- I06FAF88A
- IED0B6639
- IC40894A6
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:00:17.012856
  last_modified_at: 2023-01-04 13:00:17.012872
  collections:
  - Longchen Rabjam Series
  - Works of Tibetan Masters
alignment_to_base:
  I06FAF88A/7751: F38B
  IED0B6639/736E: F38B
  IC40894A6/37F9: F38B
